/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BuyNow: typeof import('./src/components/compounds/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./src/components/compounds/CardStatisticsVertical.vue')['default']
    ErrorHeader: typeof import('./src/components/compounds/ErrorHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/components/compounds/ThemeSwitcher.vue')['default']
  }
}
